#!/bin/bash
OUT=out
CONC=$(cat /proc/cpuinfo | grep process | wc -l)
FORKKEY=FORKBEGIN
DEBUG=0
SHOW=1
echod()
{
	if [ "$DEBUG" == "1" ]; then 
		echo "$@" >&2
	fi
}
check()
{
	if [ ! -d "$OUT" ]; then
		mkdir -p $OUT
	fi
	MAX=$#
	echod "Setting new MAX=$MAX"
}
show()
{
	if [ "$SHOW" == 1 ]; then
		clear
		if [ "$DEBUG" == "1" ]; then
			grep -re ".*" out/ | sed -e 's|:|\t|'
		fi
		echo "Jobs running: $JCOUNT "
	fi
}
run_forks()
{
	JCOUNT="-1"
	let CPID=0
	Q=0
	while [ "$Q" -ne "1" ]; do
		if [ "$JCOUNT" -lt "$CONC" ]; then
			let CPID=CPID+1
			if [ "$JCOUNT" -lt "$MAX" ]; then
				echod "JCOUNT=$JCOUNT < CONC=$CONC --> starting new task"
				# Setting parameters of running process:
				PARAMS="$1"
				if [ ! -z "$PARAMS" ]; then
					shift
					# Running process
					DATE=$(date +"%Y%m%d%H%M%S")
					bash -c "$0 $FORKKEY $PARAMS" > $OUT"/"$0"_"$PARAMS"_at_"$DATE".txt" &
				fi
			fi
		fi
		J=$(jobs -r)
		JCOUNT=$(echo -e "$J" | wc -l)
		show
		if [ -z "$J" ] && [ -z "$1" ]; then
			Q=1
		fi
		sleep .01
	done
	echo "All complete."
}
main()
{
	if [ "$1" == "$FORKKEY" ]; then
		shift
		fork_body "$@"
	else
		check "$@"
		run_forks "$@"
	fi
}
