#!/bin/bash
#
#
PATH_TO_LIB=~/.scripts/shell/justrun
source $PATH_TO_LIB/justrun-lib
fork_body()
{
	echo "Script started with parameters: \"$@\" at $(date) with PID=$$"
	# ... actions ...
	sleep $[ ( $RANDOM % 5 )  + 1 ]s
	echo "Complete at $(date)."
}
main "$@"
